spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: spring-cloud-config-client10

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:7001/eureka

info:
  app.name: spring-cloud-config-client-dev
  company: gaochaojin
---
server:
  port: 8102
spring:
  profiles: test
  application:
    name: spring-cloud-config-client10

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:7001/eureka

info:
  app.name: spring-cloud-config-client-dev
  company: gaochaojin